plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: ["_backup", "CNAME", "LICENSE.md", "README.md", "css/includes", "backup"]

markdown: kramdown
permalink: pretty

sass:
    sass_dir: ./css

host: https://visualisierung.dgfk.net
url: https://visualisierung.dgfk.net

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: ""
      lang: "de"
      description: "Kommission für Kartographie und Forschung - Deutsche Gesellschaft für Kartographie, DGfK"
      socialMedia: "/images/social_media.jpg"